/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: StarWars-Universe (https://sketchfab.com/SWU)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/tie-fighter-c306f5183f364176912d782b19474781
Title: TIE Fighter
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TieFighter(props) {
    const { nodes, materials } = useGLTF('/models/vehicles/imperial/tie_fighter.glb')
    return (
        <group scale={0.007} {...props} dispose={null} position={[0, 2.17, 0]}>
            <group rotation={[-Math.PI / 2, 0, -0.2]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group position={[103.342, -207.109, 30.918]}>
                        <group
                            position={[-56.768, -28.895, -0.598]}
                            rotation={[Math.PI / 2, 0, 0]}
                            scale={4.974}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Material1_1.geometry}
                                material={materials['1_-_Standard.1']}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Material1_2.geometry}
                                material={materials['1_-_Standard.1']}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Material1_3.geometry}
                                material={materials['1_-_Standard.1']}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Material1_4.geometry}
                                material={materials['1_-_Standard.1']}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Material1_5.geometry}
                                material={materials['1_-_Standard.1']}
                            />
                        </group>
                        <group position={[7.487, -9.873, -0.871]} rotation={[-Math.PI / 2, 0, 0]} scale={0.964}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Material1_7.geometry}
                                material={materials['1_-_Standard.1']}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Material2.geometry}
                                material={materials['2_-_Standard']}
                            />
                        </group>
                        <group
                            position={[-166.61, 3.749, -0.628]}
                            rotation={[Math.PI, -Math.PI / 2, 0]}
                            scale={[1.135, 1.135, 0.218]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Material1_10.geometry}
                                material={materials['1_-_Standard']}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Material2_1.geometry}
                                material={materials['7_-_Standard']}
                            />
                        </group>
                        <group
                            position={[152.459, 3.749, -0.628]}
                            rotation={[Math.PI, -Math.PI / 2, 0]}
                            scale={[1.135, 1.135, 0.218]}>
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Material1_11.geometry}
                                material={materials['1_-_Standard']}
                            />
                            <mesh
                                castShadow
                                receiveShadow
                                geometry={nodes.Material2_2.geometry}
                                material={materials['7_-_Standard']}
                            />
                        </group>
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Material1.geometry}
                            material={materials['1_-_Standard']}
                            position={[-145.057, 7.051, 20.708]}
                            rotation={[0, 0.227, 0]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Material1_6.geometry}
                            material={materials['7_-_Standard.1']}
                            position={[1.004, 48.237, 44.084]}
                            scale={[0.44, 0.505, 0.44]}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Material1_8.geometry}
                            material={materials['3_-_Standard']}
                            position={[-15.106, 9.364, 31.589]}
                            rotation={[0, 0, -1.966]}
                            scale={3.003}
                        />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Material1_9.geometry}
                            material={materials['2_-_Standard']}
                            position={[1.082, 2.743, 55.943]}
                            rotation={[-Math.PI, 0, 0]}
                            scale={[4.094, 4.094, 1.507]}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('./../../assets/vehicles/imperial/tie_fighter.glb')
